#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

KERNEL_DIR=build/kernel

# some hacking
mkdir -p ${KERNEL_DIR}/debian/stamps
chmod a+x ${KERNEL_DIR}/debian*/scripts/*
chmod a+x ${KERNEL_DIR}/debian*/scripts/misc/*

# kernel
pushd ${KERNEL_DIR}
unset -v ARCH KERNEL_DIR
debian/rules clean
# see https://wiki.ubuntu.com/KernelTeam/KernelMaintenance#Overriding_module_check_failures
debian/rules binary-headers binary-generic \
    do_zfs=false \
    do_dkms_nvidia=false \
    do_dkms_nvidia_server=false \
	skipabi=true \
	skipmodule=true \
	skipretpoline=true
popd
