#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

# kernel
mkdir -p build/kernel
curl -sSL -o ${DOWNLOADS}/ubuntu-kernel.tar.gz ${KERNEL_SOURCE_URL}
tar xf ${DOWNLOADS}/ubuntu-kernel.tar.gz -C ./build/kernel

# firmware
mkdir -p build/firmware
curl -sSL -o ${DOWNLOADS}/firmware.tar.gz ${FIRMWARE_URL}
tar -xf ${DOWNLOADS}/firmware.tar.gz -C ./build/firmware

# patches
pushd .
cd build/
for p in patches/*.patch; do
    echo "patching $p"
    patch -p1 -i $p
done
popd

