#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

GENERIC_HEADERS_DIR=dist/generic/headers
GENERIC_MAIN_DIR=dist/generic/main
GENERIC_EXTRA_DIR=dist/generic/modules-extra

mkdir -p ${GENERIC_HEADERS_DIR} ${GENERIC_MAIN_DIR} ${GENERIC_EXTRA_DIR}

KERNEL_BASE_DIR=build/kernel/debian
FIRMWARE_BASE_DIR=build/firmware

# headers
rsync -av ${KERNEL_BASE_DIR}/linux-headers-*[0-9]/usr/ ${GENERIC_HEADERS_DIR}/usr/
rsync -av ${KERNEL_BASE_DIR}/linux-headers-*-generic/usr/ ${GENERIC_HEADERS_DIR}/usr/
rsync -av ${KERNEL_BASE_DIR}/linux-headers-*-generic/lib/ ${GENERIC_HEADERS_DIR}/lib/

# main modules and vmlinuz and firmware
IMAGE_GENERIC_DIR=${KERNEL_BASE_DIR}/linux-image-unsigned-*-generic
if [ ! -d ${IMAGE_GENERIC_DIR} ]; then
    IMAGE_GENERIC_DIR=${KERNEL_BASE_DIR}/linux-image-*-generic
fi
rsync -av ${IMAGE_GENERIC_DIR}/boot/ ${GENERIC_MAIN_DIR}/boot/
rsync -av ${KERNEL_BASE_DIR}/linux-modules-[0-9]*-generic/boot/ ${GENERIC_MAIN_DIR}/boot/
rsync -av ${KERNEL_BASE_DIR}/linux-modules-[0-9]*-generic/lib/ ${GENERIC_MAIN_DIR}/lib/
rsync -av ${FIRMWARE_BASE_DIR}/ ${GENERIC_MAIN_DIR}/lib/firmware/

# extra modules
rsync -av ${KERNEL_BASE_DIR}/linux-modules-extra-*-generic/lib/ ${GENERIC_EXTRA_DIR}/lib/

# package artifacts
mkdir -p dist/artifacts

pushd ${GENERIC_HEADERS_DIR}
time sh -xc "tar cJf ../../artifacts/kernel-headers-generic_${ARCH}.tar.xz ."
popd

pushd ${GENERIC_MAIN_DIR}
time sh -xc "tar cJf ../../artifacts/kernel-generic_${ARCH}.tar.xz ."
popd

pushd ${GENERIC_EXTRA_DIR}
time sh -xc "tar cJf ../../artifacts/kernel-extra-generic_${ARCH}.tar.xz ."
popd
